module.exports = {
  TO_MAIN: 'TO_MAIN',
  FROM_MAIN: 'FROM_MAIN',
  TO_CURRENT_PAGE: 'TO_CURRENT_PAGE',
  FROM_CURRENT_PAGE: 'FROM_CURRENT_PAGE',
  PAGE_COLLECTION: 'pages.db',
  PROJECT_COLLECTION: 'projects.db',
  LABEL_COLLECTION: 'labels.db',
  TO_CURRENT_LABEL: 'TO_CURRENT_LABEL',
  FROM_CURRENT_LABEL: 'FROM_CURRENT_LABEL'
}
