export default [
  {
    key: 'red',
    name: 'red',
    type: 'normal',
    title: 'Red',
    required: false,
    unique: false,
    color: '#fc605b',
    describe: 'Default',
  },
  {
    key: 'orange',
    name: 'orange',
    type: 'normal',
    title: 'Orange',
    required: false,
    unique: false,
    color: '#fdbc40',
    describe: 'Default',
  },
  {
    key: 'green',
    name: 'green',
    type: 'normal',
    title: 'Green',
    required: false,
    unique: false,
    color: '#34c84a',
    describe: 'Default',
  },
  {
    key: 'blue',
    name: 'blue',
    type: 'normal',
    title: 'Blue',
    required: false,
    unique: false,
    color: '#57acf5',
    describe: 'Default',
  },
];
